---
- name: First Error Handling
  hosts: planet_express

  tasks:
          - name: Block begins here
            block: 
              - shell: "echo 'My single task ran' > example.txt"
              - shell: "echo 'My second task ran' >> example.txt"
              - shell: "echo 'My third task ran' >> example.txt"
